export const EXCHANGE_RATE_MWK_TO_CNY = 0.0041;
export const EXCHANGE_RATE_CNY_TO_MWK = 1 / EXCHANGE_RATE_MWK_TO_CNY;
export const EXCHANGE_RATE_MWK_TO_ZMW = 0.015;
export const EXCHANGE_RATE_ZMW_TO_MWK = 1 / EXCHANGE_RATE_MWK_TO_ZMW;